// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protocolbuf/IMRequest.proto

package cn.tzqwz.common.im.protocolbuf;

public final class IMRequestProto {
  private IMRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IMRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.tzqwz.common.im.protocolbuf.IMRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string requestid = 1;</code>
     */
    boolean hasRequestid();
    /**
     * <code>optional string requestid = 1;</code>
     */
    java.lang.String getRequestid();
    /**
     * <code>optional string requestid = 1;</code>
     */
    com.google.protobuf.ByteString
        getRequestidBytes();

    /**
     * <code>optional int32 reqtype = 2;</code>
     */
    boolean hasReqtype();
    /**
     * <code>optional int32 reqtype = 2;</code>
     */
    int getReqtype();

    /**
     * <code>optional string reqmsg = 3;</code>
     */
    boolean hasReqmsg();
    /**
     * <code>optional string reqmsg = 3;</code>
     */
    java.lang.String getReqmsg();
    /**
     * <code>optional string reqmsg = 3;</code>
     */
    com.google.protobuf.ByteString
        getReqmsgBytes();
  }
  /**
   * Protobuf type {@code cn.tzqwz.common.im.protocolbuf.IMRequest}
   */
  public  static final class IMRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.tzqwz.common.im.protocolbuf.IMRequest)
      IMRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IMRequest.newBuilder() to construct.
    private IMRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IMRequest() {
      requestid_ = "";
      reqmsg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new IMRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IMRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              requestid_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              reqtype_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              reqmsg_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.tzqwz.common.im.protocolbuf.IMRequestProto.internal_static_cn_tzqwz_common_im_protocolbuf_IMRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.tzqwz.common.im.protocolbuf.IMRequestProto.internal_static_cn_tzqwz_common_im_protocolbuf_IMRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest.class, cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest.Builder.class);
    }

    private int bitField0_;
    public static final int REQUESTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object requestid_;
    /**
     * <code>optional string requestid = 1;</code>
     */
    public boolean hasRequestid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string requestid = 1;</code>
     */
    public java.lang.String getRequestid() {
      java.lang.Object ref = requestid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string requestid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequestidBytes() {
      java.lang.Object ref = requestid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQTYPE_FIELD_NUMBER = 2;
    private int reqtype_;
    /**
     * <code>optional int32 reqtype = 2;</code>
     */
    public boolean hasReqtype() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 reqtype = 2;</code>
     */
    public int getReqtype() {
      return reqtype_;
    }

    public static final int REQMSG_FIELD_NUMBER = 3;
    private volatile java.lang.Object reqmsg_;
    /**
     * <code>optional string reqmsg = 3;</code>
     */
    public boolean hasReqmsg() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string reqmsg = 3;</code>
     */
    public java.lang.String getReqmsg() {
      java.lang.Object ref = reqmsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          reqmsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string reqmsg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getReqmsgBytes() {
      java.lang.Object ref = reqmsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqmsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, reqtype_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, reqmsg_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, reqtype_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, reqmsg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest)) {
        return super.equals(obj);
      }
      cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest other = (cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest) obj;

      if (hasRequestid() != other.hasRequestid()) return false;
      if (hasRequestid()) {
        if (!getRequestid()
            .equals(other.getRequestid())) return false;
      }
      if (hasReqtype() != other.hasReqtype()) return false;
      if (hasReqtype()) {
        if (getReqtype()
            != other.getReqtype()) return false;
      }
      if (hasReqmsg() != other.hasReqmsg()) return false;
      if (hasReqmsg()) {
        if (!getReqmsg()
            .equals(other.getReqmsg())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRequestid()) {
        hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
        hash = (53 * hash) + getRequestid().hashCode();
      }
      if (hasReqtype()) {
        hash = (37 * hash) + REQTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getReqtype();
      }
      if (hasReqmsg()) {
        hash = (37 * hash) + REQMSG_FIELD_NUMBER;
        hash = (53 * hash) + getReqmsg().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.tzqwz.common.im.protocolbuf.IMRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.tzqwz.common.im.protocolbuf.IMRequest)
        cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.tzqwz.common.im.protocolbuf.IMRequestProto.internal_static_cn_tzqwz_common_im_protocolbuf_IMRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.tzqwz.common.im.protocolbuf.IMRequestProto.internal_static_cn_tzqwz_common_im_protocolbuf_IMRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest.class, cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest.Builder.class);
      }

      // Construct using cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        requestid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        reqtype_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        reqmsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.tzqwz.common.im.protocolbuf.IMRequestProto.internal_static_cn_tzqwz_common_im_protocolbuf_IMRequest_descriptor;
      }

      @java.lang.Override
      public cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest getDefaultInstanceForType() {
        return cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest.getDefaultInstance();
      }

      @java.lang.Override
      public cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest build() {
        cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest buildPartial() {
        cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest result = new cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requestid_ = requestid_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.reqtype_ = reqtype_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.reqmsg_ = reqmsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest) {
          return mergeFrom((cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest other) {
        if (other == cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest.getDefaultInstance()) return this;
        if (other.hasRequestid()) {
          bitField0_ |= 0x00000001;
          requestid_ = other.requestid_;
          onChanged();
        }
        if (other.hasReqtype()) {
          setReqtype(other.getReqtype());
        }
        if (other.hasReqmsg()) {
          bitField0_ |= 0x00000004;
          reqmsg_ = other.reqmsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object requestid_ = "";
      /**
       * <code>optional string requestid = 1;</code>
       */
      public boolean hasRequestid() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string requestid = 1;</code>
       */
      public java.lang.String getRequestid() {
        java.lang.Object ref = requestid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            requestid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string requestid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRequestidBytes() {
        java.lang.Object ref = requestid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string requestid = 1;</code>
       */
      public Builder setRequestid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        requestid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestid = 1;</code>
       */
      public Builder clearRequestid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestid_ = getDefaultInstance().getRequestid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestid = 1;</code>
       */
      public Builder setRequestidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        requestid_ = value;
        onChanged();
        return this;
      }

      private int reqtype_ ;
      /**
       * <code>optional int32 reqtype = 2;</code>
       */
      public boolean hasReqtype() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 reqtype = 2;</code>
       */
      public int getReqtype() {
        return reqtype_;
      }
      /**
       * <code>optional int32 reqtype = 2;</code>
       */
      public Builder setReqtype(int value) {
        bitField0_ |= 0x00000002;
        reqtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 reqtype = 2;</code>
       */
      public Builder clearReqtype() {
        bitField0_ = (bitField0_ & ~0x00000002);
        reqtype_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object reqmsg_ = "";
      /**
       * <code>optional string reqmsg = 3;</code>
       */
      public boolean hasReqmsg() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string reqmsg = 3;</code>
       */
      public java.lang.String getReqmsg() {
        java.lang.Object ref = reqmsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            reqmsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string reqmsg = 3;</code>
       */
      public com.google.protobuf.ByteString
          getReqmsgBytes() {
        java.lang.Object ref = reqmsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reqmsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string reqmsg = 3;</code>
       */
      public Builder setReqmsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        reqmsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string reqmsg = 3;</code>
       */
      public Builder clearReqmsg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        reqmsg_ = getDefaultInstance().getReqmsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string reqmsg = 3;</code>
       */
      public Builder setReqmsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        reqmsg_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.tzqwz.common.im.protocolbuf.IMRequest)
    }

    // @@protoc_insertion_point(class_scope:cn.tzqwz.common.im.protocolbuf.IMRequest)
    private static final cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest();
    }

    public static cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<IMRequest>
        PARSER = new com.google.protobuf.AbstractParser<IMRequest>() {
      @java.lang.Override
      public IMRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IMRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IMRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IMRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.tzqwz.common.im.protocolbuf.IMRequestProto.IMRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_tzqwz_common_im_protocolbuf_IMRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_tzqwz_common_im_protocolbuf_IMRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037src/protocolbuf/IMRequest.proto\022\036cn.tz" +
      "qwz.common.im.protocolbuf\"?\n\tIMRequest\022\021" +
      "\n\trequestid\030\001 \001(\t\022\017\n\007reqtype\030\002 \001(\005\022\016\n\006re" +
      "qmsg\030\003 \001(\tB0\n\036cn.tzqwz.common.im.protoco" +
      "lbufB\016IMRequestProto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cn_tzqwz_common_im_protocolbuf_IMRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_tzqwz_common_im_protocolbuf_IMRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_tzqwz_common_im_protocolbuf_IMRequest_descriptor,
        new java.lang.String[] { "Requestid", "Reqtype", "Reqmsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
