// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protocolbuf/IMResponse.proto

package cn.tzqwz.common.im.protocolbuf;

public final class IMResponseProto {
  private IMResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IMResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.tzqwz.common.im.protocolbuf.IMResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string responseid = 1;</code>
     */
    boolean hasResponseid();
    /**
     * <code>optional string responseid = 1;</code>
     */
    java.lang.String getResponseid();
    /**
     * <code>optional string responseid = 1;</code>
     */
    com.google.protobuf.ByteString
        getResponseidBytes();

    /**
     * <code>optional int32 restype = 2;</code>
     */
    boolean hasRestype();
    /**
     * <code>optional int32 restype = 2;</code>
     */
    int getRestype();

    /**
     * <code>optional string resmsg = 3;</code>
     */
    boolean hasResmsg();
    /**
     * <code>optional string resmsg = 3;</code>
     */
    java.lang.String getResmsg();
    /**
     * <code>optional string resmsg = 3;</code>
     */
    com.google.protobuf.ByteString
        getResmsgBytes();
  }
  /**
   * Protobuf type {@code cn.tzqwz.common.im.protocolbuf.IMResponse}
   */
  public  static final class IMResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.tzqwz.common.im.protocolbuf.IMResponse)
      IMResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IMResponse.newBuilder() to construct.
    private IMResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IMResponse() {
      responseid_ = "";
      resmsg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new IMResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IMResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              responseid_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              restype_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              resmsg_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.tzqwz.common.im.protocolbuf.IMResponseProto.internal_static_cn_tzqwz_common_im_protocolbuf_IMResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.tzqwz.common.im.protocolbuf.IMResponseProto.internal_static_cn_tzqwz_common_im_protocolbuf_IMResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse.class, cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse.Builder.class);
    }

    private int bitField0_;
    public static final int RESPONSEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object responseid_;
    /**
     * <code>optional string responseid = 1;</code>
     */
    public boolean hasResponseid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string responseid = 1;</code>
     */
    public java.lang.String getResponseid() {
      java.lang.Object ref = responseid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          responseid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string responseid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResponseidBytes() {
      java.lang.Object ref = responseid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESTYPE_FIELD_NUMBER = 2;
    private int restype_;
    /**
     * <code>optional int32 restype = 2;</code>
     */
    public boolean hasRestype() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 restype = 2;</code>
     */
    public int getRestype() {
      return restype_;
    }

    public static final int RESMSG_FIELD_NUMBER = 3;
    private volatile java.lang.Object resmsg_;
    /**
     * <code>optional string resmsg = 3;</code>
     */
    public boolean hasResmsg() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string resmsg = 3;</code>
     */
    public java.lang.String getResmsg() {
      java.lang.Object ref = resmsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          resmsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string resmsg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getResmsgBytes() {
      java.lang.Object ref = resmsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resmsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, responseid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, restype_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, resmsg_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, responseid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, restype_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, resmsg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse)) {
        return super.equals(obj);
      }
      cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse other = (cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse) obj;

      if (hasResponseid() != other.hasResponseid()) return false;
      if (hasResponseid()) {
        if (!getResponseid()
            .equals(other.getResponseid())) return false;
      }
      if (hasRestype() != other.hasRestype()) return false;
      if (hasRestype()) {
        if (getRestype()
            != other.getRestype()) return false;
      }
      if (hasResmsg() != other.hasResmsg()) return false;
      if (hasResmsg()) {
        if (!getResmsg()
            .equals(other.getResmsg())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasResponseid()) {
        hash = (37 * hash) + RESPONSEID_FIELD_NUMBER;
        hash = (53 * hash) + getResponseid().hashCode();
      }
      if (hasRestype()) {
        hash = (37 * hash) + RESTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getRestype();
      }
      if (hasResmsg()) {
        hash = (37 * hash) + RESMSG_FIELD_NUMBER;
        hash = (53 * hash) + getResmsg().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.tzqwz.common.im.protocolbuf.IMResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.tzqwz.common.im.protocolbuf.IMResponse)
        cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.tzqwz.common.im.protocolbuf.IMResponseProto.internal_static_cn_tzqwz_common_im_protocolbuf_IMResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.tzqwz.common.im.protocolbuf.IMResponseProto.internal_static_cn_tzqwz_common_im_protocolbuf_IMResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse.class, cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse.Builder.class);
      }

      // Construct using cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        responseid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        restype_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        resmsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.tzqwz.common.im.protocolbuf.IMResponseProto.internal_static_cn_tzqwz_common_im_protocolbuf_IMResponse_descriptor;
      }

      @java.lang.Override
      public cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse getDefaultInstanceForType() {
        return cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse.getDefaultInstance();
      }

      @java.lang.Override
      public cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse build() {
        cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse buildPartial() {
        cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse result = new cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.responseid_ = responseid_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.restype_ = restype_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.resmsg_ = resmsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse) {
          return mergeFrom((cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse other) {
        if (other == cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse.getDefaultInstance()) return this;
        if (other.hasResponseid()) {
          bitField0_ |= 0x00000001;
          responseid_ = other.responseid_;
          onChanged();
        }
        if (other.hasRestype()) {
          setRestype(other.getRestype());
        }
        if (other.hasResmsg()) {
          bitField0_ |= 0x00000004;
          resmsg_ = other.resmsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object responseid_ = "";
      /**
       * <code>optional string responseid = 1;</code>
       */
      public boolean hasResponseid() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string responseid = 1;</code>
       */
      public java.lang.String getResponseid() {
        java.lang.Object ref = responseid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            responseid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string responseid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResponseidBytes() {
        java.lang.Object ref = responseid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string responseid = 1;</code>
       */
      public Builder setResponseid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        responseid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string responseid = 1;</code>
       */
      public Builder clearResponseid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        responseid_ = getDefaultInstance().getResponseid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string responseid = 1;</code>
       */
      public Builder setResponseidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        responseid_ = value;
        onChanged();
        return this;
      }

      private int restype_ ;
      /**
       * <code>optional int32 restype = 2;</code>
       */
      public boolean hasRestype() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 restype = 2;</code>
       */
      public int getRestype() {
        return restype_;
      }
      /**
       * <code>optional int32 restype = 2;</code>
       */
      public Builder setRestype(int value) {
        bitField0_ |= 0x00000002;
        restype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 restype = 2;</code>
       */
      public Builder clearRestype() {
        bitField0_ = (bitField0_ & ~0x00000002);
        restype_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object resmsg_ = "";
      /**
       * <code>optional string resmsg = 3;</code>
       */
      public boolean hasResmsg() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string resmsg = 3;</code>
       */
      public java.lang.String getResmsg() {
        java.lang.Object ref = resmsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            resmsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string resmsg = 3;</code>
       */
      public com.google.protobuf.ByteString
          getResmsgBytes() {
        java.lang.Object ref = resmsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resmsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string resmsg = 3;</code>
       */
      public Builder setResmsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        resmsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string resmsg = 3;</code>
       */
      public Builder clearResmsg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        resmsg_ = getDefaultInstance().getResmsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string resmsg = 3;</code>
       */
      public Builder setResmsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        resmsg_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.tzqwz.common.im.protocolbuf.IMResponse)
    }

    // @@protoc_insertion_point(class_scope:cn.tzqwz.common.im.protocolbuf.IMResponse)
    private static final cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse();
    }

    public static cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<IMResponse>
        PARSER = new com.google.protobuf.AbstractParser<IMResponse>() {
      @java.lang.Override
      public IMResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IMResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IMResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IMResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.tzqwz.common.im.protocolbuf.IMResponseProto.IMResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_tzqwz_common_im_protocolbuf_IMResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_tzqwz_common_im_protocolbuf_IMResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n src/protocolbuf/IMResponse.proto\022\036cn.t" +
      "zqwz.common.im.protocolbuf\"A\n\nIMResponse" +
      "\022\022\n\nresponseid\030\001 \001(\t\022\017\n\007restype\030\002 \001(\005\022\016\n" +
      "\006resmsg\030\003 \001(\tB1\n\036cn.tzqwz.common.im.prot" +
      "ocolbufB\017IMResponseProto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cn_tzqwz_common_im_protocolbuf_IMResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_tzqwz_common_im_protocolbuf_IMResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_tzqwz_common_im_protocolbuf_IMResponse_descriptor,
        new java.lang.String[] { "Responseid", "Restype", "Resmsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
