###web服务端口
server:
  port: 8400
###web服务名称
spring:
  application:
    name: im-forward-route
  ###redis配置信息
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
###zookeeper配置信息
zk:
  ###连接地址
  connect:
    address: 127.0.0.1:2181
    ###连接超时时间
    timeout: 15000
  ###路由节点信息
  root:
    node: /route
route:
  algorithm:
    ###轮询机制
    way: cn.tzqwz.common.route.algorithm.loop.LoopRouteHandle
    ###随机路由
    ##way: cn.tzqwz.common.route.algorithm.random.RandomRouteHandle